Add auth, ws, profile, orders
vladislavkuc/stellar-burger pull request #3
Opened 2023-02-06 06:33 UTC by vladislavkuc

2023-02-06 07:18 UTC, kyzinatra commented on src/pages/login.js
> +import React from 'react';
Можно лучше: стоит, как и в случае с обычными компонентами, разделить страницы по папкам, со своими стилями и компонентом страницы. Так они будут лучше отсортированны и проект будет более единообразным

2023-02-06 07:18 UTC, kyzinatra commented on src/pages/login.js
> +        errorText={state.errorText}
Отлично! Очень круто, что вы сделали `errorText`

2023-02-06 07:20 UTC, kyzinatra commented on src/pages/register.js
> +      .then(data => {
Надо исправить: регистрация не проходит с ошибкой `message: "Email, password and name are required fields"`

2023-02-06 07:27 UTC, kyzinatra commented on src/pages/profile.js
> +        setState({
Надо исправить: если токен истек, то `getUsetInfo` не сработает

2023-02-06 07:28 UTC, kyzinatra commented on src/services/api.js
> +    method: 'GET',
Надо исправить: Стоит везде где вы используете `accessToken` проверять его. Для этого стоит создать отдельный метод `requestWithRefersh`

2023-02-06 07:31 UTC, kyzinatra commented on src/pages/resetpass.js
> +    );
Надо исправить: необходимо вынести всю логику редиректа пользователя по тому авторизирован он или нет в `ProtectedRoute`, чтобыф не думать об этом при написании самой страницы. Для этого можно создать либо отдельные 2 компоненты, либо добавить какой-нибудь проп к существующему компоненту

2023-02-06 07:36 UTC, kyzinatra commented on src/components/protected-route-element/protected-route-element.js
> +}
Надо исправить: стоит проверить именно валидность токена, а не просто его наличие. Для этого стоит отправить запрос на `/auth/user`

2023-02-06 07:43 UTC, kyzinatra commented
Выглядит очень круто! Видно, что проделана большая работа. Отличная верстка всех страниц и реализвация роутинга. Есть некоторые замечание по авторизцаии, но в целом, сама система взаимодействия и redux сделаны хорошо. Стоит поправить мелкие ошибки и ваша работа будет принята

Что важно исправить:

- регистрация не проходит с ошибкой `message: "Email, password and name are required fields"`
- если токен истек, то `getUsetInfo` не сработает
- Стоит везде где вы используете `accessToken` проверять его. Для этого можно создать отдельный метод `requestWithRefersh`
- необходимо вынести всю логику редиректа пользователя по тому авторизирован он или нет в `ProtectedRoute`, чтобыф не думать об этом при написании самой страницы. Для этого можно создать либо отдельные 2 компоненты, либо добавить какой-нибудь проп к существующему компоненту
-  стоит проверить именно валидность токена, а не просто его наличие. Для этого стоит отправить запрос на `/auth/user`

Можно лучше:

- Cтоит, как и в случае с обычными компонентами, разделить страницы по папкам, со своими стилями и компонентом страницы. Так они будут лучше отсортированны и проект будет более единообразным

Что понравилось:

- Очень круто, что вы сделали `errorText`

Обратите внимание, что работа принимается только после исправления всех `«Надо исправить»`.

2023-02-07 02:44 UTC, kyzinatra commented
Вы отлично потрудились.

Поздравляю! Ваша работа принята.
Удачного дальнейшего обучения

2023-02-07 15:53 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализованы веб-сокеты;
- Есть страница ленты заказов;

### **Но есть несколько замечаний, которые нужно исправить:**

- Исправьте последнюю ошибку в консоли: <https://disk.yandex.com/i/**28vcdEjY2ZYqEA>.

- На странице `лента заказов`, не отображается контент:<https://disk.yandex.com/i/5dQqcWlrNAxYEg>. Аналогично и со страницей История заказов `profile/orders`;

- Авторизированный пользователь не может попасть на роуты, которые обёрнуты в `protect-route`;

- По чек-листу, сокет-соединение закрывается, когда пользователь покидает их страницы с ним. <https://disk.yandex.com/i/vIbnUR7Hv4Ej8w>;

- Сокет соединение `/orders` должно открываться на странице `profile/orders`, а у вас открывается на странице `/profile`;

- У вас должно быть подключено расширение Redux Devtools, которое работает в режиме разработки;

- В запрос `POST /order - Отправка заказа в burger-constructor`, вы должно добавлять хедер с полем `authorization` в который кладётся токен пользователя.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

### **После исправления всех замечаний, работа будет принята)**

2023-02-07 15:53 UTC, ArslanDev666 commented on src/components/protected-route-element/protected-route-element.js
> +        if (res.succes) { setAuth(true) }
**Надо исправить:**

Из-за ошибки в слове `succes`, авторизированный пользователь не может попасть на защищённые роуты.

2023-02-07 15:53 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.js
> +    if (localStorage.getItem('refreshToken')) {
**Можно лучше:**

Лучше сделать отдельный стейт в редаксе для этого, и просто его переиспользовать) а не достовать каждый раз данные из localStorage.

2023-02-07 15:53 UTC, ArslanDev666 commented on src/components/order-items/order-items.js
> +  }, [ingredientsList]);
**Надо исправить:**

Неиспользуемый код лучше удалить.

2023-02-07 15:53 UTC, ArslanDev666 commented on src/pages/feed.js
> +            </ul>
**можно лучше:**

Здесь и далее.

Фильтрацию лучше сделать до рендера.

2023-02-07 15:53 UTC, ArslanDev666 commented on src/pages/login.js
> +  })
**Можно лучше**

Можно сделать универсальный кастомный хук для контроля любого количества инпутов в любых формах:

```js
export function useForm(inputValues) {
  const [values, setValues] = useState(inputValues);

  const handleChange = event => {
    const { value, name } = event.target;
    setValues({ ...values, [name]: value });
  };
  return { values, handleChange, setValues };
}
```

Этот код помещают в отдельный файл useForm.js в папке hooks и импортируют функцию туда, где нужно контролировать инпуты

И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:

```js
const { values, handleChange, setValues } = useForm({...});
```

2023-02-07 15:53 UTC, ArslanDev666 commented on src/pages/order.js
> +  }, [ingredientsList]);
**Можно лучше:**

Почему бы сразу не сделать фильтрацию, тут излишне делать дополнительный useEffect и стейт.

2023-02-08 04:49 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец!**

- Практически все замечания с прошлого ревью были исправлены.

### **Но есть несколько замечаний, которые нужно исправить:**

- Если авторизированный пользователь перезагрузит страницу, то он не сможет больше попасть на роуты, которые обёрнуты в `protect-route`;

- По чек-листу: При клике по заказу открывается модальное окно с информацией о заказе и происходит переход на маршрут `/feed/:id` или `/profile/orders/:id` в зависимости от того, на какой странице пользователь кликнул по заказу. При прямом переходе на эти маршруты открывается страница заказа.
  
  У вас открывается просто новая страница, а также если попытаться открыть ссылку типа `feed:id` или `profile/orders/:id` в новой вкладке, то ничего не будет отображаться.

  <https://disk.yandex.com/i/_6O9U5AEn6tVgg>

2023-02-08 17:28 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Практически все замечания с прошлого ревью были исправлены.

### **Рекомендую исправить:**

- После нажатия на кнопку `Войти` пользователя должны перекидывать на главную страницу, или на ту, к которой ранее был доступ закрыт (зависит от сценария) <https://disk.yandex.com/i/WDSnGuDwfb9sEg>;

2023-02-27 14:59 UTC, merged